name: Code Quality

on:
  push:
    branches:
      - master
      - release/*  # this is a backup. prefer publishing using a tagged master.
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master

jobs:
  codestyle:
    name: codestyle
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        # https://github.com/actions/python-versions/blob/main/versions-manifest.json
        python-version: [ "3.10" ]

    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - uses: tsuyoshicho/action-mypy@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          mypy_flags: '--strict --disallow-untyped-defs --check-untyped-defs'
          workdir: dataclasses_json
